site_name: 'python-app-poc'
site_description: 'Main documentation for the python-app'
repo_url: https://github.com/rafaelvieira96/python-app-poc
edit_uri: edit/develop/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'